root = "."
tmp_dir = "tmp"

[build]
# 只需要监听 .go 文件的变化
include_ext = ["go"]
# 忽略这些文件夹
exclude_dir = ["assets", "tmp", "vendor", "docs"]
# 主程序入口
cmd = "go build -o ./tmp/main ./cmd/api"
# 二进制文件路径
bin = "./tmp/main"
# 自定义参数
full_bin = "./tmp/main"
# 延迟时间
delay = 1000
# 是否包含测试文件
include_dir = []
# 是否包含隐藏文件
include_file = []
# 是否监控子目录
follow_symlink = false
# 日志颜色
log = "air.log"
# 是否发送系统通知
send_interrupt = true
# 是否在终端显示日志
stop_on_error = true

[log]
# 是否显示日志时间
time = true

[color]
# 自定义日志颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
clear_on_rebuild = true