version: '3.8'

services:
  api:
    image: ${ECR_REGISTRY:-nicheflow}/nicheflow-api:${IMAGE_TAG:-latest}
    container_name: nicheflow-api
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP 端口
    environment:
      - APP_ENV=production
      - TZ=Asia/Shanghai
      - AWS_REGION=${AWS_REGION:-ap-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ~/.ssh:/root/.ssh:ro
    networks:
      - nicheflow-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  nicheflow-network:
    driver: bridge 