version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nicheflow-api:latest
    container_name: nicheflow-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - ./.env.production:/etc/nicheflow/.env
    networks:
      - nicheflow-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  nicheflow-network:
    driver: bridge 