app:
  name: NicheFlow
  version: 0.1.0
  mode: development
  port: 8080
  
database:
  driver: postgres
  host: localhost
  port: 5432
  name: nicheflow
  user: postgres
  password: ${DB_PASSWORD}
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

redis:
  host: localhost
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0

jwt:
  secret: ${JWT_SECRET}
  expire: 24h
  issuer: nicheflow

openai:
  api_key: ${OPENAI_API_KEY}
  organization: ${OPENAI_ORG_ID}
  model: gpt-4-turbo-preview
  max_tokens: 2000
  temperature: 0.7

anthropic:
  api_key: ${ANTHROPIC_API_KEY}
  model: claude-3-opus
  max_tokens: 2000
  temperature: 0.7

cors:
  allowed_origins:
    - http://localhost:3000
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Authorization
    - Content-Type
  allow_credentials: true
  max_age: 300 