app:
  name: NicheFlow
  version: 0.1.0
  
database:
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

openai:
  model: gpt-4-turbo-preview
  max_tokens: 2000
  temperature: 0.7

anthropic:
  model: claude-3-opus
  max_tokens: 2000
  temperature: 0.7

middleware:
  rate_limit:
    enabled: true
    limit: 100
    duration: 1m
  cors:
    allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allow_headers:
      - Authorization
      - Content-Type
      - X-Clerk-User-Id
    max_age: 300 