app:
  env: ${APP_ENV}
  name: NicheFlow
  version: 0.1.0
  mode: ${APP_MODE}
  port: ${APP_PORT}
  
database:
  driver: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  ssl_mode: ${DB_SSL_MODE}
  ssl_tunnel: ${DB_SSL_TUNNEL}
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}
  ssl_tunnel: ${REDIS_SSL_TUNNEL}
  tls_enable: ${REDIS_TLS_ENABLE}

jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}
  issuer: nicheflow

openai:
  api_key: ${OPENAI_API_KEY}
  organization: ${OPENAI_ORG_ID}
  model: gpt-4-turbo-preview
  max_tokens: 2000
  temperature: 0.7

anthropic:
  api_key: ${ANTHROPIC_API_KEY}
  model: claude-3-opus
  max_tokens: 2000
  temperature: 0.7

cors:
  allowed_origins:
    - ${CORS_ALLOWED_ORIGINS}
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Authorization
    - Content-Type
  allow_credentials: true
  max_age: 300

oauth:
  base_url: ${APP_BASE_URL}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${APP_BASE_URL}/api/auth/callback/google
    scopes:
      - openid
      - profile
      - email
  github:
    client_id: ${GITHUB_CLIENT_ID}
    client_secret: ${GITHUB_CLIENT_SECRET}
    redirect_uri: ${APP_BASE_URL}/api/auth/callback/github
    scopes:
      - user
      - user:email 